### ISSUE TITLE
error 500 supabaseUrl is required 

### ISSUE THREAD

**Issue by Jupriadi** [zackha/supaAuth#3]
i got error seen in tittle above. please help me
![Screen Shot 2023-06-20 at 13 07 40](https://github.com/zackha/supaAuth/assets/27283144/fcf64232-c168-4317-9fa0-511d4db3c00e)

**Comment by zackha** [comment]
Hi @Jupriadi, in order to run the supaAuth project, you need to open a supabase account. Then, you need to write your project's API information into a file named .env.example. (Don't forget to remove the word .example at the end)

![supabase](https://github.com/zackha/supaAuth/assets/79358543/3a9091d6-746c-4f2c-b605-1196dd6f881f)

![.env](https://github.com/zackha/supaAuth/assets/79358543/4dcf3828-6b1c-4fac-a607-fc14ecfdd574)

Best Regards,

**Comment by Jupriadi** [comment]
thank youe.. this is my first time learning about supabase with nuxtjs.. now i've do that, but now i just see loading when i try to register..
![Screen Shot 2023-06-20 at 16 33 10](https://github.com/zackha/supaAuth/assets/27283144/39f5f396-257d-44f4-87e3-838717cdeacf)

and i didn't see any errors in console...

**Comment by Jupriadi** [comment]
thank you before @zackha
